function [mask, handle_objects] = createGoldenMask(RGB)
% Auto-generated by colorThresholder app

I = RGB;

channel1Min = 55.000;
channel1Max = 91.000;

channel2Min = 41.000;
channel2Max = 74.000;

channel3Min = 0.000;
channel3Max = 27.000;

sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
           (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
           (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);

BW = sliderBW;

imClean = imfill(BW, 'holes');
imClean = imclearborder(imClean);
imClean = imfill(imClean,26,'holes');

stats = regionprops(imClean, 'Area','Circularity','PixelList');
handle_objects = struct([]);

threshold_area = 1500;
num = 0;

for i = 1:numel(stats)
    if stats(i).Area > threshold_area
        num = num + 1;
        handle_objects(num).Area = stats(i).Area;
        handle_objects(num).Circularity = stats(i).Circularity;
        handle_objects(num).PixelList = stats(i).PixelList;
    end
end

handle_objects = handle_objects(1:num);
mask = imClean;
num = length(handle_objects);

end
